### ISSUE TITLE
Ideally use underscores for crate names

### ISSUE THREAD

**Issue by gilescope** [facebookexperimental/mononoke#4]
It looks like the community is finally settling on '_' in crate names rather than '-'.  
(See https://github.com/rust-lang/cargo/pull/1443 )

Would be great to make the change as my understanding is that nothing is published to crates.io yet.

**Comment by sid0** [comment]
Hi @gilescope, thanks for the report! According to the link you included, package names (which are what the directory names represent) are allowed to have hyphens in them. My own taste is for hyphens over underscores. Is there some other evidence (perhaps statistical?) which shows that most package names have underscores and not hyphens?

Note that since this is an application and not a library, the only public APIs Mononoke will support are over wire protocols. This also means that we don't plan to publish Mononoke on crates.io.

**Comment by gilescope** [comment]
The most compelling argument for '_' rather than '-' is that "extern crate crate-with-hyphen;" isn't allowed, so you end up having a hyphen in the Cargo.toml and an underscore in the extern statement.
As the crates are not being published, it matters less.
